baseurl = "https://www.skanwarulislam.com"
title = "Anwar's Home"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Sk Mohd Anwarul Islam"
    description = "Anwar's personal website"
    keywords = "blog,developer,personal"
    info = "Technology Enthusiast, DevOps, Bad Ass Developer"
    avatarurl = "images/avatar.jpg"
    footercontent = "Life is a complex maze."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/skanwarulislam"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab"
    weight = 2
    url = "https://gitlab.com/skanwar"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/skanwar_islam"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/skmohdanwarulislam/"
[[params.social]]
    name = "Facebook"
    icon = "fab fa-facebook"
    weight = 5
    url = "https://www.facebook.com/sk.mohd.anwarul.islam"


[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About Me"
        weight = 1
        url = "about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "posts/"

        [[languages.en.menu.main]]
        name = "interest"
        weight = 3
        url = "projects/"

        [[languages.en.menu.main]]
        name = "Contact me"
        weight = 5
        url = "contact/"


    [languages.bn]
        languagename = "Bengali"
        title = "আনোয়ারের হোম"

        [languages.bn.params]
            author = "শেখ মোঃ আনোয়ারুল ইসলাম"
            info = "টেকনোলজি আগ্রহী, অভিজ্ঞ প্রোগ্রামার"
            description = "আনোয়ারের ওয়েবসাইট"
            keywords = "blog,desenvolvedor,pessoal"
            footercontent = "জীবন একটি কঠিন গোলক ধাঁধা"

        [languages.bn.menu]

            [[languages.bn.menu.main]]
            name = "আমার সম্পর্কে"
            weight = 1
            url = "about/"

            [[languages.bn.menu.main]]
            name = "ব্লগ"
            weight = 2
            url = "posts/"

            [[languages.bn.menu.main]]
            name = "আকাম"
            weight = 3
            url = "projects/"

            [[languages.bn.menu.main]]
            name = "যোগাযোগ"
            weight = 5
            url = "contact/"
